# Generated by Django 5.0.7 on 2025-05-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_orderupdate_order_razorpay_order_id_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.order'),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
